# x=open("name.txt","x")
# x=open("name.txt","w")
# x.write("my name is anu")
# x.write("\nIam from plkd")
# # x.close()
# x=open("name.txt","a")
# x.write("\nmy favourite colour is blue")
# x.close()
# x=open("name.txt","r")
# print(x.read())
# x.close()
# x=open("name.txt","r")
# print(x.read(5))
# x.close()
# x=open("name.txt","r")
# print(x.readline())
# print(x.readline())
# x.close()
# import os
# # os.remove("colour.txt")
# os.rmdir("folder 1")