import math
# x=int(input("enter radius of a circle: "))
# print(math.pi*x**2,"area of a circle")
# x=int(input("enter radius of a sphere: "))
# print(math.pi*4*x**2,"area of a sphere")
# x=int(input("enter radius of a sphere: "))
# print(math.pi*4/3*x**3,"volume of a sphere")
# x=int(input("enter radius of a cylinder: "))
# y=int(input("enter height of a cylinder: "))
# a=math.pi*2*x*(x+y)
# print(a,"area of a cylinder")
x=int(input("enter radius of a cone: "))
y=int(input("enter height of a cone: "))
a=1/3*math.pi*x**2*y
print(a,"volume of a cone")
# x=int(input("enter radius"))
# print(math.pi*pow(x,2))
# x=int(input("enter a radius"))
# print(math.pi*4/3*pow(x,3))