# x=open("colour.txt","x")
x=open("colour.txt","w")
x.write("colour is blue")
x.close()
x=open("colour.txt","r")
print(x.read(6))
x.close()
x=open("colour.txt","a")
x.write("\ncolour is red")
x.close()
x=open("colour.txt","r")
print(x.read())
x.close()
x=open("colour.txt","r")
print(x.readline())
x.close()
