# x=open("course.txt","w")
# x.write("mba")
# x.close()
# x=open("course.txt","r")
# p=x.read()
# y=open("vehicles.txt","x")
# y=open("vehicles.txt","w")
# y.write(p)
# y.close()
# y=open("vehicles.txt","r")
# print(y.read())
# y.close()
# x=open("file1.txt","x")
x=open("file1.txt","w")
x.write("good morning")
x=open("file1.txt","r")
b=x.read()
# y=open("file2.txt","x")
y=open("file2.txt","w")
y.write(" have a nice day")
y=open("file2.txt","r")
m=y.read()
# z=open("file3.txt","x")
z=open("file3.txt","w")
z.write(b)
z.write(m)
